import Navbar from '@/components/Navbar'
import './globals.css'
import { Merriweather } from 'next/font/google'
import Head from 'next/head'

const merriweather = Merriweather({ subsets: ['latin'], weight: ['300', '400', '700', '900'] })


export const metadata = {
  title: "Mario's Wood-Fired Mobile Pizza and Catering",
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html className={merriweather.className} lang="en">
      <Head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  )
}
